### ISSUE TITLE
heimdall response returns 200 status but return data in stream format

### ISSUE THREAD

**Issue by MuthukumarHelios** [gojek/heimdall#65]
Current Working Code which having Raw http and heimdallHttpClient (internal Api)
the below gist code having both success case and error case 

https://gist.github.com/MuthukumarHelios/79ef131001a9f8fb5b2b4232c63c6b50

**Comment by rShetty** [comment]
@MuthukumarHelios Can you use gist to paste some sample code which is failing ?

**Comment by MuthukumarHelios** [comment]
The current Response which i was getting is 
--> happening only for using heimdall 
`[
    "<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center>    <h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
]`

**Comment by MuthukumarHelios** [comment]
@rShetty see the edit which having code sample

**Comment by rShetty** [comment]
@MuthukumarHelios I am getting 200 OK with Heimdall, not sure what is the problem you are facing ? Can you elaborate

**Comment by MuthukumarHelios** [comment]
https://user-images.githubusercontent.com/17043792/55023833-a727ed80-5023-11e9-94f6-74485a78413f.png --> response i am geeting it after using heimdall
