### ISSUE TITLE
Misleading example in README.md

### ISSUE THREAD

**Issue by flof** [gojek/heimdall#76]
In one of the examples in the README.md the client gets configured with `hystrix.WithHystrixTimeout(1100)`. This is misleading because it would be interpreted as 1100 nanoseconds and not milliseconds. And since heimdall converts this duration at some point to milliseconds, the duration drops to 0 because of rounding. Which causes a default duration of 1000ms to take effect. 
So everybody who uses this example gets a timeout of 1000ms and not 1100ms.
I suggest changing this to `hystrix.WithHystrixTimeout(1100 * time.Millisecond)`.

**Comment by rShetty** [comment]
@flof Can you raise a PR with changes for the same. Will have a look at it
