### ISSUE TITLE
Cannot import v5.1.0 due to "non optimal" go.mod

### ISSUE THREAD

**Issue by gunturaf** [gojek/heimdall#79]
I am using go1.14.
I tried to import v5.1.0 with this command: 
```
go get -u github.com/gojek/heimdall@v5.1.0
```
and it gave me this error:

```
go get github.com/gojek/heimdall@v5.1.0: github.com/gojek/heimdall@v5.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5
```

As stated in [go mod wiki page](https://github.com/golang/go/wiki/Modules#semantic-import-versioning), any package with major version larger than v0 and v1 must include its major version in the module name.

So [the statement here](https://github.com/gojek/heimdall/blob/v5.1.0/go.mod#L1) `module github.com/gojektech/heimdall` should be appended with `/v5` so that it would become `module github.com/gojektech/heimdall/v5`.

I don't know whether this change would broke backward compatibility for imports.
Example: will `import "github.com/gojektech/heimdall/httpclient"` be changed to `import "github.com/gojektech/heimdall/v5/httpclient"` and all will be ok?

If all is OK I can make a PR to this.

**Comment by mrz1836** [comment]
I'm experiencing the same issue when I try to use `v5.1.0`

**Comment by rsimkin** [comment]
This issue is actual to me too. How i can upgrade library to 5.1.0 correctly using `go get`?

**Comment by btamadio** [comment]
I'm also unable to import v5.1.0. https://github.com/gojek/heimdall/pull/80 seems to be a good fix.

**Comment by rShetty** [comment]
#80 fixes this. closing this
