### ISSUE TITLE
Constant backoff actually has 0 backoff on first retry

### ISSUE THREAD

**Issue by btamadio** [gojek/heimdall#82]
When attempting to use constant backoff strategy, I found that on the first retry of a request, the actual backoff time is 0. That's because on the first retry the client calls `c.retrier.NexInterval(0)` so constantBackoff.Next(0) returns 0:

https://github.com/gojek/heimdall/blob/16e67fd885aa9cb5b9d2257936e8e8c301eba52a/backoff.go#L34

**Comment by btamadio** [comment]
The same thing happens when using exponentialBackoff:

https://github.com/gojek/heimdall/blob/16e67fd885aa9cb5b9d2257936e8e8c301eba52a/backoff.go#L60

**Comment by rShetty** [comment]
@btamadio Thanks for pointing this out. Can you raise a PR for the same, will have a look

**Comment by btamadio** [comment]
Here's an example demonstrating the bug:

```go
func main() {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(500)
	}))
	defer s.Close()
	cli := httpclient.NewClient(
		httpclient.WithRetryCount(3),
		httpclient.WithHTTPClient(s.Client()),
		httpclient.WithRetrier(
			heimdall.NewRetrier(
				heimdall.NewConstantBackoff(
					2*time.Second,
					2*time.Millisecond,
				),
			),
		),
	)
	cli.AddPlugin(plugins.NewRequestLogger(os.Stdout, os.Stderr))
	_, _ := cli.Get(s.URL, nil)
}
```

The first retry happens with zero backoff. The backoff is only applied starting from the second retry, as you can see from the timestamps:
```
21/May/2020 10:53:39 GET http://127.0.0.1:51137 500 [0ms]
21/May/2020 10:53:39 GET http://127.0.0.1:51137 500 [0ms]
21/May/2020 10:53:41 GET http://127.0.0.1:51137 500 [1ms]
21/May/2020 10:53:43 GET http://127.0.0.1:51137 500 [0ms]
```
