### ISSUE TITLE
Incorrect formula for exponential backoff

### ISSUE THREAD

**Issue by btamadio** [gojek/heimdall#83]
Need to change the first plus sign here to a multiplication:

https://github.com/gojek/heimdall/blob/16e67fd885aa9cb5b9d2257936e8e8c301eba52a/backoff.go#L63

Exponential backoff with exponent factor 2 should be initialBackoff * 2^n.

**Comment by rShetty** [comment]
@btamadio Thanks for pointing this out. Can you raise a PR for the same, will have a look

**Comment by rShetty** [comment]
@btamadio Thanks for pointing this out. Can you raise a PR for the same, will have a look

**Comment by btamadio** [comment]
Here's a snippet illustrating the issue. With min=1second, max=8 seconds, and exp. factor=2,
I would expect the backoff times to be 1, 2, 4, 8, 8 seconds:

```go
func main() {
	fmt.Println("testing constant backoff ...")
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(500)
	}))
	defer s.Close()
	cli := httpclient.NewClient(
		httpclient.WithRetryCount(5),
		httpclient.WithHTTPClient(s.Client()),
		httpclient.WithRetrier(
			heimdall.NewRetrier(
				heimdall.NewExponentialBackoff(
					1*time.Second,
					8*time.Second,
					2,
					2*time.Millisecond,
				),
			),
		),
	)
	cli.AddPlugin(plugins.NewRequestLogger(os.Stdout, os.Stderr))
	_, _ = cli.Get(s.URL, nil)
}
```

Timestamps show this is not happening:

```
21/May/2020 11:18:37 GET http://127.0.0.1:51397 500 [0ms]
21/May/2020 11:18:37 GET http://127.0.0.1:51397 500 [0ms]
21/May/2020 11:18:38 GET http://127.0.0.1:51397 500 [0ms]
21/May/2020 11:18:39 GET http://127.0.0.1:51397 500 [0ms]
21/May/2020 11:18:40 GET http://127.0.0.1:51397 500 [1ms]
21/May/2020 11:18:41 GET http://127.0.0.1:51397 500 [0ms]
```

**Comment by rShetty** [comment]
@btamadio Thanks for the PR. Have added a few comments

**Comment by btamadio** [comment]
> @btamadio Thanks for the PR. Have added a few comments

Took a look but couldn't find any comments on the PR.
